import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Container } from '../shared/styles/styles';
import SwiperCore, { Navigation, Pagination } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/swiper-bundle.css";
import Carousel from '../shared/components/Carousel';



const inter = Inter({ subsets: ['latin'] })

const images = [
  'https://github.com/kayqueprogram/Yuki-onna-discord.js/raw/main/.github/bot-card.png',
  'https://github.com/kayqueprogram/Yuki-onna-discord.js/raw/main/.github/bot-card.png',
  'https://github.com/kayqueprogram/Yuki-onna-discord.js/raw/main/.github/bot-card.png',
  'https://github.com/kayqueprogram/Yuki-onna-discord.js/raw/main/.github/bot-card.png',
];

export default function Home() {

  return (
    <>
      <Head>
        <title>Omar Donato Bassani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>
         <h1> Carousel</h1>
        </header>
        <Container>

          <div>
           
            <Carousel images={images} />
          </div>

        </Container>
      </div>
      <footer>footer</footer>

    </>

  )
}
